/**
 * Generates per-component CSS files from existing *.tv.ts configs in ui/.
 * Reads .base / .variants directly off the tv() return value — no changes
 * to the source files needed.
 *
 * Run: npx tsx docs/scripts/generate-components.ts
 */

import { writeFileSync } from "fs";
import { join } from "path";

import { button } from "../src/components/ui/button/button.tv";
import { badge } from "../src/components/ui/badge/badge.tv";
import { card, cardHeader, cardTitle, cardDescription, cardContent, cardFooter } from "../src/components/ui/card/card.tv";
import { toggleTrack, toggleThumb } from "../src/components/ui/toggle/toggle.tv";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type TvInstance = {
  base?: string;
  variants?: Record<string, Record<string, string>>;
};


// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toClasses(v: string | string[]): string {
  return Array.isArray(v) ? v.join(" ") : v;
}

// Rename shadcn "default" variant to "primary" in CSS output (DaisyUI convention)
const modifierAliases: Record<string, string> = { default: "primary" };

function generateCSS(name: string, tv: TvInstance): string {
  const base = toClasses((tv.base as any) ?? "").trim();

  const lines: string[] = [
    `/* DO NOT EDIT — generated by docs/scripts/generate-components.ts`,
    ` * Source: docs/src/components/ui/${name}/${name}.tv.ts`,
    ` * Re-run the script to regenerate. */`,
    `@layer components {`,
  ];

  if (base) {
    lines.push(`  .${name} {`);
    lines.push(`    @apply ${base};`);
    lines.push(`  }`);
  }

  if (tv.variants) {
    for (const [group, values] of Object.entries(tv.variants)) {
      const defaultVal = (tv as any).defaultVariants?.[group];
      lines.push(``);
      for (const [modifier, classes] of Object.entries(values)) {
        const cls = toClasses(classes as any).trim();
        if (!cls) continue;
        // Skip "default" size modifiers — bake them into base instead
        if (modifier === "default" && modifier === defaultVal && group === "size") {
          const baseIdx = lines.findIndex((l) => l.includes(`  .${name} {`));
          if (baseIdx !== -1) {
            lines[baseIdx + 1] = lines[baseIdx + 1].replace(";", ` ${cls};`);
          }
          continue;
        }
        const cssModifier = modifierAliases[modifier] ?? modifier;
        lines.push(`  .${name}-${cssModifier} {`);
        lines.push(`    @apply ${cls};`);
        lines.push(`  }`);
      }
    }
  }

  lines.push(`}`);
  return lines.join("\n") + "\n";
}

// ---------------------------------------------------------------------------
// Write — each CSS file lives next to its *.tv.ts source
// ---------------------------------------------------------------------------

const uiDir = join(import.meta.dirname, "../src/components/ui");

const entries: Array<{ folder: string; name: string; tv: TvInstance }> = [
  { folder: "button", name: "btn", tv: button as any },
  { folder: "badge",  name: "badge",  tv: badge as any },
  { folder: "card",   name: "card",         tv: card as any },
  { folder: "card",   name: "card-header",  tv: cardHeader as any },
  { folder: "card",   name: "card-title",   tv: cardTitle as any },
  { folder: "card",   name: "card-description", tv: cardDescription as any },
  { folder: "card",   name: "card-content", tv: cardContent as any },
  { folder: "card",   name: "card-footer",  tv: cardFooter as any },
  { folder: "toggle", name: "toggle-track", tv: toggleTrack as any },
  { folder: "toggle", name: "toggle-thumb", tv: toggleThumb as any },
];

for (const { folder, name, tv } of entries) {
  const css = generateCSS(name, tv);
  const outPath = join(uiDir, folder, `${name}.css`);
  writeFileSync(outPath, css, "utf8");
  console.log(`wrote ${outPath}`);
}

console.log(`\nImport in global.css:\n`);
const folders = [...new Set(entries.map((e) => e.folder))];
for (const folder of folders) {
  const names = entries.filter((e) => e.folder === folder).map((e) => e.name);
  for (const name of names) {
    console.log(`  @import "../components/ui/${folder}/${name}.css" layer(components);`);
  }
}
